### TYPE YOUR NAME HERE: Gabriel Ferraz

## ISM 5644 - Programming for Analytics

## Assignment 2 - Coding Section

### Important: Assignments are to be completed and submitted *individually* - i.e., you are <u>not</u> allowed to work in groups.
### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. The corresponding question text for each code cell is provided above the cell.

### Questions:

#### 1. Assume that there exists a file named “attendance.txt” in the local disk. Each line of the file represents the attendance for a class on a particular day. Each line starts with a day of the week, followed by a comma separated list of names. Assume that the names in each line are unique. Write a program that can find the day that had the most students attending. Report the day and the number of students that attended. An example input / output is as follows:
#### Input (text file in the local disk):
Monday, Joe, Bill, Sarah<br>
Tuesday, Joe, Bill, Sarah, Fred<br>
Wednesday, Joe, Fred

#### Output:
Tuesday had the highest attendance with 4 students.

In [19]:
attendance_file = open('attendance.txt', 'r')
lines = attendance_file.readlines()
highest_day = ''
count = -1

for i in lines:
    line_list = i.strip().split(',')
    day = line_list[0].strip()
    stud_count = len(line_list) - 1

    if stud_count > count:
        count = stud_count
        highest_day = day
print(highest_day,'had the highest attendance with',count,'students.')
attendance_file.close()

Tuesday had the highest attendance with 4 students.

#### 2. Consider the input from the question above. Write a program that: 1) reports the attendance count of each unique student, and 2) prints out the student that had the highest attendance along with his/her attendance count. An example output is as follows:

#### Output:
Joe || Attendance count: 3<br>
Bill || Attendance count: 2<br>
Sarah || Attendance count: 2<br>
Fred || Attendance count: 2<br>
\--------------------------<br>
Highest attendance count: 3 || Student: Joe

#### Optional:
For additional difficulty and practice, assume that there can be multiple students who had the same highest attendance count (e.g., Joe and Bill both had 3 days of attendance). The program should print out: "Highest attendance count: 3 || Student(s): Joe, Bill" in that situation.

In [233]:
attendance_file = open('attendance.txt','r')
student_name = []
student_count = []

for i in lines:
    line_list = i.strip().split(',')
    students = line_list[1:]
    for student in students:
        name = student.strip()
        if name in student_name:
            idx = student_name.index(name)
            student_count[idx] += 1
        else:
            student_name.append(name)
            student_count.append(1)

best_student = ''
most_count = -1
for i in range(len(student_name)):
    print(student_name[i],'||', 'Attendance count:',student_count[i])
    if student_count[i] > most_count:
        most_count = student_count[i]
        best_student = student_name[i]
print('Highest attendance count:',most_count,'||','Student:',best_student)
attendance_file.close()

Joe || Attendance count: 3
Bill || Attendance count: 2
Sarah || Attendance count: 2
Fred || Attendance count: 2
Highest attendance count: 3 || Student: Joe

#### 3. Write a function that takes a list as an argument and returns a list that only contains the items that occurred exactly once in the original list.

In [51]:
L = [4,23,37,9,37,10,9]
def no_copy(alist):
    new_list = []
    for i in alist:
        if alist.count(i) == 1:
            new_list.append(i)
    return new_list
no_copy(L)

[4, 23, 10]

#### 4. Suppose that you are the manager of a manufacturing firm who is trying to determine the optimal price of a product based on demand. The relationship between price and demand is as follows: 
Demand = 800 – 10 x Price
#### Each product costs 50 USD to manufacture. The profit of the company is calculated as: 
Profit = (Price – Cost per item) x Demand
#### Write a function that, given a single price input, will first calculate its demand and then return the profit amount. Then, search a range of prices (using the function above) to identify the optimal price that will provide you the maximum profit. Notice that the range is limited, because the demand goes negative if price exceeds a certain threshold. Print out this price and the maximum profit amount.

In [230]:
cost = 50

def manufacturing(price):
    demand = 800 - 10 * price
    profit = (price - cost) * demand
    return profit
    
print('Lowest profit until 0:',manufacturing(50.1))
print('Highest profit until 0:',manufacturing(79.9))

maximum = 0
optimal = 0

for price in range(50,80):
    if manufacturing(price) > maximum:
        maximum = manufacturing(price)
        optimal = price
print('Optimal price:',optimal)
print('Maximum profit:',maximum)

Lowest profit until 0: 29.900000000000425
Highest profit until 0: 29.900000000000006
Optimal price: 65
Maximum profit: 2250

#### 5. Please download the data set titled "mortgage_default.csv" from the course website to use with this question. The data includes information on past or active home loans offered by a financial institution. 
#### It includes demographics info as well as descriptive characteristics of the loan. The outcome column shows if the loan went default or not. The status column shows whether the loan is current (active) or has been closed (either paid-off or went default). 
#### Please perform the tasks listed below using the Pandas Library. The steps should be completed in sequence.

#### 5.1. Data Exploration
* Read the file as a DataFrame
* Display the column names
* Display the size (how many rows and columns)
* Display the first 10 rows
* Display the summary statistics for numeric variables
* Display the number of loans offered in each state
* Among the non-active loans (i.e., status is <u>not</u> active), display what percentage of them went default


#### 5.2. Cleaning and Filtering
* Remove all active loans from the data frame
* Remove the column Median_state_inc from the data frame
* Display all loans that went default AND whose applicants had a credit score of 700 or above
* Display all loans that were offered in Florida AND whose applicants were older than the average applicant age in the data

#### 5.3. Grouping
* Group the data by outcome and find the average loan amount (Ln_Orig), the average credit score (Credit_score), and the applicant's total monthly income (Tot_mthly_incm) for each group

In [73]:
import pandas as pd
df = pd.read_table('mortgage_default.csv',delimiter = ',')
df.columns
df.shape
df.head(10)
df.describe
df['State'].value_counts()
notactive = df.loc[df['Status'] != 'Active']
percent = (notactive['Status'] == 'Default').mean() * 100
print(percent)

5.537190082644628

In [108]:
active = df.loc[df['Status'] == 'Active']
df.drop(active.index)
df.drop(['Median_state_inc'],axis=1)
df.loc[(df['Credit_score']>700) & (df['Status'] == 'Default')]
olderaverage = df['Bo_Age'].mean()
#df.loc[(df['State'] == 'FL') & (df['Bo_Age']>df['Bo_Age'].mean()),:]
df.loc[(df['State'] == 'FL') & (df['Bo_Age']>olderaverage),:]

,Bo_Age,Ln_Orig,Credit_score,First_home,Tot_mthly_debt_exp,Tot_mthly_incm,orig_apprd_val_amt,pur_prc_amt,Status,OUTCOME,State,Median_state_inc
1,40,168701.0,765,N,595,3200,118933,118933,Active,non-default,FL,40171
111,37,289750.0,670,N,324,1056,80000,80000,Active,non-default,FL,40171
112,37,288000.0,665,N,0,1058,65000,65000,Active,non-default,FL,40171
181,39,128250.0,729,N,672,2900,82000,82000,Active,non-default,FL,40171
192,39,216000.0,701,N,802,3188,108000,108000,Active,non-default,FL,40171
...,...,...,...,...,...,...,...,...,...,...,...,...
14871,42,55800.0,714,N,3174,11500,341000,340900,Pay-off,non-default,FL,40171
14937,42,250400.0,650,N,2062,5025,355000,355000,Pay-off,non-default,FL,40171
14947,66,173200.0,662,N,0,10000,360000,359352,Pay-off,non-default,FL,40171
14972,37,320000.0,682,N,10589,5025,365000,365000,Pay-off,non-default,FL,40171
15030,42,157500.0,640,N,4934,11375,385000,385000,Pay-off,non-default,FL,40171

In [107]:
dfgroup = df.groupby('OUTCOME')
dfgroup[['Ln_Orig','Credit_score','Tot_mthly_incm']].mean()

                   Ln_Orig  Credit_score  Tot_mthly_incm
OUTCOME
default      165255.559627    654.231343     4502.087065
non-default  153146.314209    688.579554     5038.950173

#### 6. You are given a list variable containing the daily closing stock prices for a specific company over a 5-day period:<br>
stock_prices = [150.25, 153.40, 149.80, 152.10, 155.00]<br>

Write a program that repeatedly prompts the user to enter an integer index to retrieve the stock price for a specific day. Because users can make mistakes, wrap your input conversion and list access within a try-except block to build a robust program that will not crash:  
1. Successful Retrieval: If the user enters a valid index, print the corresponding price and exit the program.
2. Invalid Data Type: If the user enters non-numeric text (e.g., "abc"), catch the resulting ValueError, print "Error: Please enter a valid integer index.", and prompt them again.
3. Out-of-Bounds Index: If the user enters a numeric index that falls outside the boundaries of the list (e.g., 10 or -6), catch the resulting IndexError, print "Error: Index out of range. Please choose a valid day index.", and prompt them again.<br><br>
   
The loop must continue running until a valid element is successfully retrieved from the list.

In [235]:
stock_prices = [150.25, 153.40, 149.80, 152.10, 155.00]

while True:
    idx = input('Give me an integer index:')
    try:
        idx = int(idx)
        print('Stock price of the day:',stock_prices[idx])
        break
    except ValueError:
        print('Error: Please enter a valid integer index.')
    except IndexError:
        print('Error: Index out of range. Please choose a valid day index.')

Give me an integer index: abc

Error: Please enter a valid integer index.

Give me an integer index: -10

Error: Index out of range. Please choose a valid day index.

Give me an integer index: 6

Error: Index out of range. Please choose a valid day index.

Give me an integer index: 1

Stock price of the day: 153.4