### TYPE YOUR NAME HERE: Gabriel Ferraz

# ISM 5644 - Programming for Analytics

## Lab Exercise: Introduction to Pandas

### Overview:
This lab covers operations related to reading and manipulating data with Pandas.

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. The corresponding question text for each code cell is provided above the cell. Once you have completed the lab, you should publish your notebook code (the code in the .ipynb file) as a "Secret Gist" on your GitHub repository and obtain the Gist ID.

### Submission Format:
There are two deliverables of this lab: 1) the Gist ID and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding lab submission link by the due date indicated on Canvas.

### Important: Do <u>not</u> forget to run the cells before submitting your work.

### Data Description:

The data set that will be used in this lab is named "cerealData.csv". Please download it from the course website. In this data set, each observation corresponds to a particular brand of cereal. The "mfr" column indicates the manufacture, where A = American Home Food Products; G = General Mills; K = Kelloggs; N = Nabisco; P = Post; Q = Quaker Oats; R = Ralston Purina. Type can be cold ("C") or hot ("H"). Ratings are calculated by Consumer Reports. Other column names are self-explanatory and indicate different ingredients in the cereal.

### Questions: Please note that there are multiple steps in each question. You can run each step individually (before moving on to the next one) to make sure that your output is correct.

#### 1. Data Exploration
* Read the file as a DataFrame
* Display the column names
* Display the size (how many rows and columns)
* Display the first 10 rows
* Rename column "mfr" to "manufacturer"
* Drop column "sodium" from the data
* Drop the rows indexed 0 to 5
* Display the first 10 rows
* Display the summary statistics for numeric variables
* Count the number of cereals that each manufacturer has in the data

In [2]:
import pandas as pd
df = pd.read_table('cerealData.csv', delimiter = ',')
df.columns
df.shape
df.head(10)
df = df.rename(columns={'mfr': 'manufacturer'})
df = df.drop(['sodium'], axis=1)
df = df.drop(df.index[0:6])
df.head(10)
df.describe()
df['manufacturer'].value_counts()

manufacturer
K    21
G    21
P     9
R     7
Q     7
N     5
A     1
Name: count, dtype: int64

#### 2. Selecting from the Data
* Display the sugar amount of "Froot_Loops" (under the "sugars" column)
* Change the "rating" of "Cap'n'Crunch" to 100.0 (since it is the best cereal ever)
* Slice the first 10 observations and the first 5 columns from the data and display the values (do <u>not</u> update the existing data frame)
    * Hint: You can use .iloc() for this purpose.

In [3]:
df.set_index('name', inplace=True)
print('Sugar Amount for Froot Loops:', df.loc['Froot_Loops','sugars'])
df.loc["Cap'n'Crunch",'rating'] = 100.0
print("Cap'n'Crunch rating:", df.loc["Cap'n'Crunch",'rating'])
df.iloc[0:11, 0:5]

Sugar Amount for Froot Loops: 13
Cap'n'Crunch rating: 100.0

                      manufacturer type  calories  protein  fat
name
Apple_Jacks                      K    C       110        2    0
Basic_4                          G    C       130        3    2
Bran_Chex                        R    C        90        2    1
Bran_Flakes                      P    C        90        3    0
Cap'n'Crunch                     Q    C       120        1    2
Cheerios                         G    C       110        6    2
Cinnamon_Toast_Crunch            G    C       120        1    3
Clusters                         G    C       110        3    2
Cocoa_Puffs                      G    C       110        1    1
Corn_Chex                        R    C       110        2    0
Corn_Flakes                      K    C       100        2    0

#### 3. Filtering
* Display the name, sugar level, and rating of cereals that contain more than 10 grams of sugar
* Find the average rating of the cereals above (i.e., those that contain more than 10 grams of sugar). Compare this number to the average rating of cereals that contain less than 10 grams of sugar.
* Display cereal names, manufacturer names, and rating levels of cereals that contain more than the average calorie amount
* Drop the observations that were manufactured by "Ralston Purina" (indicated as "R" in the manufacturer column)
    * Hint: You can also interpret this statement as selecting all observations that were NOT manufactured by "Ralston Purina"
* Select and display all observations that were manufactured by "General Mills" (indicated as "G") AND that have a rating greater than the average rating score in the data
    * Hint: Remember to use the "&" symbol (instead of AND) when combining multiple conditions in Pandas.

In [68]:
#df = df.reset_index()
df.loc[df['sugars']>10,['name','sugars','rating']]
above_sugars = df.loc[(df['sugars']>10)]
above_sugars_avg_rat = above_sugars['rating'].mean()
below_sugars = df.loc[(df['sugars']<10)]
below_sugars_avg_rat = below_sugars['rating'].mean()
print('Cereals above 10 grams of sugar:',above_sugars_avg_rat)
print('Cereals below 10 grams of sugar:',below_sugars_avg_rat)

df.loc[df['calories']>df['calories'].mean(),['name','manufacturer','rating']]
df_R = df.loc[df['manufacturer'] == 'R']
df.drop(df_R.index)

df.loc[(df['manufacturer'] == 'G') & (df['rating']>df['rating'].mean()),:]

Cereals above 10 grams of sugar: 34.55434433333333
Cereals below 10 grams of sugar: 47.46842273913044

,level_0,index,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
5,5,5,Cheerios,G,C,110,6,2,2.0,17.0,1,25,50.764999
65,65,65,Total_Whole_Grain,G,C,100,3,1,3.0,16.0,3,100,46.658844
69,69,69,Wheaties,G,C,100,3,1,3.0,17.0,3,25,51.592193

#### 4. Grouping
* Group data by the manufacturer and find the average sugar level and the average rating for each group
* Select the observations with high rating (rating > 50) and find out how many were manufactured by each manufacturer.

In [82]:
dfgroup = df.groupby('manufacturer')
dfgroup[['sugars','rating']].mean()

final = df.loc[df['rating']>50, ['manufacturer']]
final['manufacturer'].value_counts()

manufacturer
N    5
Q    4
K    4
P    3
G    2
A    1
Name: count, dtype: int64