### TYPE YOUR NAME HERE: Gabriel Ferraz

## ISM 5644 - Programming for Analytics

## Exam - Coding Section

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. Once you have completed the test, you should publish your notebook code (the code in the .ipynb file) as a "Secret Gist" on your GitHub repository and obtain the Gist ID.

### Submission Format:
There are two deliverables of this exam: 1) the Gist ID and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding submission link.

### Important: Do not forget to <u>run</u> the cells before submitting the document.

#### Q1. Use the cell below to enter your code for this question. Step 1:

Write a function that takes two inputs:

1) a string consisting of a single letter (e.g., 'e')

2) a long string consisting of some letters (e.g., 'HELLo WORld')

and counts how many times the single letter (1st input) occurs in the long string (2nd input). The function should ignore capitalization – i.e., uppercase 'E' should be counted as 'e', etc. The output of the function should be the frequency count of the letter.

Step 2:

Write a loop that iteratively calls the function you developed in the first step to count how many times each letter in a given list (e.g., ['a', 'e', 'o']) occurs in the long string consisting of some letters (2nd input of Step 1).

Below is a sample output after completing both steps.

longString = 'HELLo WORld'

aList = ['a', 'e', 'o']

Output (after defining the function and running the loop): 

The letter a occurs 0 times in the long string.

The letter e occurs 1 times in the long string.

The letter o occurs 2 times in the long string.

In [68]:
def phrase(letter,sentence):
    counter = 0
    for letter in sentence: 
        counter += 1
    return counter
phrase('t','bottle')

6

#### Q2. Use the cell below to enter your code for this question.
Assume that there exists a file named “aFile.txt” in the local disk. Write a program that prompts the user for a positive integer n as an input. The program should write the first n characters of each line in “aFile.txt” to a new file, named “newFile.txt”. The program should write the entire line, if n is greater than that line’s length. Below is a sample input and output for n = 10.

Input - aFile.txt:

First line of the file

Second line of the file

Third

Output - newFile.txt:

First line

Second lin

Third

In [53]:
aFile = open('aFile.txt.','r')
num = int(input('Give me a positive integer:'))
aFile_list = aFile.readlines()

new_list = []
num = new_list.append(i)

new_file = open('newFile.txt', 'w')
for line in new_file
    new_file.write(num)

for i in aFile_list
    if len(i)

SyntaxError: invalid character '“' (U+201C) (2675975071.py, line 1)

#### Q3. Use the cell below to enter your code for this question.

Assume that there exists a file named “numbersWords.txt” in the local disk. Each line of this file consists of some integer numbers (int) and words (str). Write a program that finds the largest number in this file, and prints out this number as well as the number of the line this number was in. Below is a sample input and output:

Input - numbersWords.txt:

random 346 numbers and

233 words are in 306

This file you 15663 need to find

4 the largest number here 592

Output:

The largest number: 15663

Found in line: 3

In [52]:
numberswords = open('numberswords.txt','r')
numberswords_list = numberswords.readlines()
maximum = 0
max_in_list = 0

for i in numberswords_list:
    i = int(i)
    if i > maximum:
        max_in_list = i
for index, i in enumerate(numberswords_list)
    

print('The largest number is:',i)
#print('Found in line:',index+1)

ValueError: invalid literal for int() with base 10: 'random 346 numbers and\n'

#### Q4 Cell 1. Use the cell below to enter your code for the 1st cell of Q4.
Question: Perform the tasks listed below using the Pandas Library. Notice that these tasks are divided into 3 cells. Please only use the designated cell area in the Jupyter file to write down your corresponding code. After importing the file at the beginning, you can continue working on the same data (i.e., you don't need to re-import the data for each individual cell).

Cell #1:

Import the downloaded data into the Python environment as a Pandas DataFrame.
Drop the column titled "GamesPlayed" from the DataFrame.
Select the first 10 observations and the first 5 columns from the data and display the values. Do NOT assign the selection to anything -- simply display the values on the screen.
Cell #2:

Display all observations that had more than 40 "Shots". Show all the columns for these observations.
Select and display all observations in Year 2011 that had more "Wins" than the average number of "Wins" for that particular year (2011).
Cell #3:

Notice that the "SeasonWinner" column indicates the season winner for a given year (The value of that column is "Y" if winner of the "Year"). Find out which team won the season the most across the years. Do the necessary operation in Pandas and print out a single output (can be a table or a string) that states the team's name and the number of season wins.

In [7]:
import pandas as pd
df = pd.read_csv('NHL_data.csv',delimiter = ',')
df.drop(['GamesPlayed'], axis = 1)
df.iloc[0:11,0:5]

    Year          Team  GamesPlayed  Wins  Losses
0   2012   LOS ANGELES           20    16       4
1   2012    NEW JERSEY           24    14      10
2   2012    NY RANGERS           20    10      10
3   2012       PHOENIX           16     9       7
4   2012    WASHINGTON           14     7       7
5   2012     NASHVILLE           10     5       5
6   2012  PHILADELPHIA           11     5       6
7   2012      ST LOUIS            9     4       5
8   2012       FLORIDA            7     3       4
9   2012        BOSTON            7     3       4
10  2012        OTTAWA            7     3       4

#### Q4 Cell 2. Use the cell below to enter your code for the 2nd cell of Q4.

In [15]:
df.loc[df['Shots']>40]
df.loc[(df['Year'] == 2011) & (df['Wins']>df['Wins'].mean()),:]

,Year,Team,GamesPlayed,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
16,2011,BOSTON,25,16,9,31.9,34.0,15.8,Y
17,2011,VANCOUVER,25,15,10,32.3,31.8,17.4,N
18,2011,TAMPA BAY,18,11,7,28.9,32.8,11.5,N
19,2011,SAN JOSE,18,9,9,36.9,31.6,15.3,N
20,2011,DETROIT,11,7,4,35.2,33.1,11.4,N
21,2011,NASHVILLE,12,6,6,29.5,29.5,10.1,N

#### Q4 Cell 3. Use the cell below to enter your code for the 3rd cell of Q4.

In [45]:
winners = df.loc[df['SeasonWinner'] == 'Y']
winners
#winners.loc[(winners['Team']]

,Year,Team,GamesPlayed,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
0,2012,LOS ANGELES,20,16,4,30.6,27.0,11.9,Y
16,2011,BOSTON,25,16,9,31.9,34.0,15.8,Y
32,2010,CHICAGO,22,16,6,31.8,29.6,10.1,Y
48,2009,PITTSBURGH,24,16,8,32.5,29.0,11.8,Y
64,2008,DETROIT,22,16,6,36.5,23.6,11.0,Y
80,2007,ANAHEIM,21,16,5,30.5,27.6,17.7,Y
96,2006,CAROLINA,25,16,9,28.8,27.0,12.8,Y
112,2004,TAMPA BAY,23,16,7,26.2,26.8,16.8,Y
128,2003,NEW JERSEY,24,16,8,28.6,26.2,8.9,Y
144,2002,DETROIT,23,16,7,29.9,24.6,13.4,Y
160,2001,COLORADO,23,16,7,26.3,27.0,11.1,Y

In [42]:
#winners = df.loc[df['SeasonWinner'] == 'Y']
#winners.loc[(winners['Team']]
groupwinners = df.groupby('SeasonWinner')
groupwinners['Team'].max()

SeasonWinner
N    WASHINGTON
Y     TAMPA BAY
Name: Team, dtype: object